# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dome' do
  pod 'ModuleCenter',:path => '../ModuleCenter'
  pod 'BusinessA',:path => '../BusinessA'
  pod 'BusinessB',:path => '../BusinessB'

end
